org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=26.2
  loader_version=0.19.3
  fabric_version=0.152.1+26.2

# Mod Properties
  group=com.presencefootsteps
  displayname=Presence Footsteps Open Source
  authors=Hurricaaane (Ha3), Sollace, AmirAli Mollaei, NGSpace
  description=An overly complicated sound mod, made slightly less complicated
  url=http://ngspace.dev

# Publishing
  minecraft_version_range=>=26.2
  modrinth_loader_type=fabric
  modrinth_project_id=hWJmdZnO

# Testing
  use_minelp=0

# Dependencies
  modmenu_version=20.0.0-beta.2
  yacl_version=3.9.4+26.2-fabric
