package eu.ha3.presencefootsteps;

import java.nio.file.Path;
import java.util.HashSet;
import java.util.Set;
import eu.ha3.presencefootsteps.config.EntitySelector;
import eu.ha3.presencefootsteps.config.JsonFile;
import eu.ha3.presencefootsteps.sound.generator.Locomotion;
import net.minecraft.entity.EntityType;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;
import net.minecraft.util.crash.CrashReportSection;
import net.minecraft.util.math.MathHelper;

public class PFConfig extends JsonFile {
    // --- client category ---
    //
    // Disables all functionality of the mod
    private boolean disabled = false;
    // Sets the player's own stance (type of footsteps to generate)
    // Options:
    //   NONE (determined by whether Mine Little Pony is installed)
    //   BIPED (always two-legged)
    //   QUADRUPED (always four-legged)
    //   FLYING (always four-legged + wings)
    //   FLYING_BIPED (always two-legged + wings)
    // Default: NONE
    private Locomotion stance = Locomotion.NONE;
    // Controls which group of entities to generate footsteps for
    // Options: ALL, PLAYERS_AND_HOSTILES, PLAYERS_ONLY
    // Default: ALL
    private EntitySelector targetEntities = EntitySelector.ALL;

    // --- volume category ---
    //
    // Sets the global footsteps volume on a value between 0% and 100%
    // Default: 70
    private int volume = 70;
    // Controls how much the footsteps sound changes when running on a percentage range between -100% to +100%
    // Default: 0
    public int runningVolumeIncrease = 0;
    // Sets the volume of your own footsteps on a value between 0% and 100%
    // Default: 100
    public int clientPlayerVolume = 100;
    // Sets the volume of other players' footsteps on a value between 0% and 100%
    // Default: 100
    public int otherPlayerVolume = 100;
    // Sets the volume of hostile mob's footsteps on a value between 0% and 100%
    // Default: 100
    public int hostileEntitiesVolume = 100;
    // Sets the volume of passive and friendly mob's footsteps on a value between 0% and 100%
    // Default: 100
    public int passiveEntitiesVolume = 100;
    // Sets the volume of sounds generated by walking on wet surfaces during rain or thunderstorms
    // Default: 50
    public int wetSoundsVolume = 50;
    // Sets the volume of sounds generated due to walking through foliage and brush
    // Default: 50
    public int foliageSoundsVolume = 100;

    // --- performance category ---
    //
    // Controls the maximum number of entities the mod can generate footsteps for in a single frame
    // Default: 50
    private int maxSteppingEntities = 50;

    // --- sound category ---
    //
    // Sets whether footsteps should be generated for other players when in multiplayer
    private boolean multiplayer = true;
    // Sets whether footsteps should be generated for other (non-player) mobs
    private boolean global = true;
    // When enabled, special footstep sounds will be generated matching the boots you are wearing.
    // Note not all types of boots are supported. Modded boots may sound strange or not work.
    private boolean footwear = true;
    // Enables a visualiser to show where sound/material checks are occuring
    private boolean visualiser = false;
    // Sets whether to block vanilla footstep sounds when generating sounds for other entities or players
    private boolean exclusive = false;

    // --- compatibility category ---
    //
    // A list of entity type for any types of mobs that should never produce footsteps. Usually should be any flying 'bird' mobs.
    // Default: minecraft:ghast, minecraft:happy_ghast, minecraft:phantom
    public final Set<Identifier> ignoredEntityTypes = new HashSet<>(Set.of(
                Identifier.ofVanilla("ghast"),
                Identifier.ofVanilla("happy_ghast"),
                Identifier.ofVanilla("phantom")
            ));


    public PFConfig(Path file) {
        super(file);
        load();
    }


    public boolean toggleMultiplayer() {
        multiplayer = !multiplayer;
        save();
        return multiplayer;
    }

    public boolean isIgnoredForFootsteps(EntityType<?> type) {
        return ignoredEntityTypes.contains(Registries.ENTITY_TYPE.getId(type));
    }

    public EntitySelector cycleTargetSelector() {
        targetEntities = EntitySelector.VALUES[(getEntitySelector().ordinal() + 1) % EntitySelector.VALUES.length];
        save();
        return targetEntities;
    }

    public Locomotion setLocomotion(Locomotion loco) {
        if (loco != getLocomotion()) {
            stance=loco;
            save();
            // pf.getEngine().reload();
        }

        return loco;
    }

    public boolean isVisualiserRunning() {
        return visualiser;
    }

    public Locomotion getLocomotion() {
        return stance == null ? Locomotion.NONE : stance;
    }

    public EntitySelector getEntitySelector() {
        return targetEntities == null ? EntitySelector.ALL : targetEntities;
    }

    public boolean getEnabledFootwear() {
        return footwear;
    }

    public boolean toggleFootwear() {
        footwear = !footwear;
        save();
        return footwear;
    }

    public boolean isExclusiveMode() {
        return exclusive;
    }

    public boolean toggleExclusiveMode() {
        exclusive = !exclusive;
        save();
        return exclusive;
    }

    public boolean getEnabledMP() {
        return multiplayer;
    }

    public int getMaxSteppingEntities() {
        return Math.max(1, maxSteppingEntities);
    }

    public boolean toggleDisabled() {
        disabled = !disabled;
        save();
        // pf.onEnabledStateChange(!disabled);
        return disabled;
    }

    public boolean setDisabled(boolean disabled) {
        if (disabled != this.disabled) {
            toggleDisabled();
        }
        return disabled;
    }

    public boolean getDisabled() {
        return disabled;
    }

    public boolean getEnabled() {
        return !disabled && getGlobalVolume() > 0;
    }

    public int getGlobalVolume() {
        return MathHelper.clamp(volume, 0, 100);
    }

    public int getRunningVolumeIncrease() {
        return MathHelper.clamp(runningVolumeIncrease, -100, 100);
    }

    public float setGlobalVolume(float volume) {
        int intVolume = volumeScaleToInt(volume);

        if (this.volume != intVolume) {
            boolean wasEnabled = getEnabled();

            this.volume = intVolume;
            save();

            //if (getEnabled() != wasEnabled) {
            //    pf.onEnabledStateChange(getEnabled());
            //}
        }

        return getGlobalVolume();
    }

    public float setRunningVolumeIncrease(float volume) {
        runningVolumeIncrease = volume > 97 ? 100 : volume < -97 ? -100 : (int)volume;
        save();
        return getRunningVolumeIncrease();
    }

    public void populateCrashReport(CrashReportSection section) {
        section.add("Disabled", getDisabled());
        section.add("Global Volume", volume);
        section.add("User's Selected Stance", getLocomotion());
        section.add("Target Selector", getEntitySelector());
        section.add("Enabled Global", global);
        section.add("Enabled Multiplayer", multiplayer);
    }

    private static int volumeScaleToInt(float volume) {
        return volume > 97 ? 100 : volume < 3 ? 0 : (int)volume;
    }
}
